url: "" # the base hostname & protocol for your site, e.g. http://example.com
baseurl: "" # the subpath of your site, e.g. /blog
title: "" # the name of your site, e.g. ACME Corp.

plugins:
  - jekyll-redirect-from

sass:
  sass_dir: assets/css

include: ["_pages"]

collections_dir:
  content

collections:
  sections:
    output: false

# Multilangue
languages:
  - fr
  - en

defaults:
  -
    scope:
      path: "_pages/fr"
      type: "pages" # a collection in your site, in plural form
    values:
      lang: "fr"
  -
    scope:
      path: "_pages/en"
      type: "pages" # a collection in your site, in plural form
    values:
      lang: "en"
